# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2024-07-20 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmaper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nmapscan',
            name='repeat',
            field=models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='nmapscan',
            name='schedule_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='schedule time'),
        ),
    ]
